# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - id: kpexec
    main: ./cmd/kpexec/main.go
    binary: kpexec
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/ssup2/kpexec/pkg/cmd/kpexec.version={{ .Tag }}
  - id: kubectl-pexec
    main: ./cmd/kpexec/main.go
    binary: kubectl-pexec
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/ssup2/kpexec/pkg/cmd/kpexec.version={{ .Tag }}
archives:
  - id: kpexec
    builds:
      - kpexec
    name_template: "kpexec_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
  - id: kubectl-pexec
    builds:
      - kubectl-pexec
    name_template: "kubectl_pexec_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
checksum:
  name_template: checksums.txt
changelog:
  sort: asc
brews:
  - name: kpexec
    ids:
      - kpexec
    tap:
      owner: ssup2
      name: homebrew-tap
    commit_author:
      name: ssup2
      email: supsup5642@gmail.com
    homepage: https://github.com/ssup2/kpexec
    description: Execute a commad in a running container with privilege
    license: MIT
    install: |
      bin.install "kpexec"
