# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go mod download
builds:
- main: ./cmd/kpexec/main.go
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
brews:
  - name: kpexec
    tap:
      owner: ssup2
      name: homebrew-tap
    commit_author:
      name: ssup2
      email: supsup5642@gmail.com
    homepage: "https://github.com/ssup2/kpexec"
    description: "Execute a commad in a running container with privilege"
    license: "MIT"
    install: |
      bin.install "kpexec"
