name: release-krew
on: 
  release: 
    types: ["published"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1 
      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.40
